Did a lot of cleanup on code and docs

diff --git a/2015-10-file-walker/Makefile b/2015-10-file-walker/Makefile
--- a/2015-10-file-walker/Makefile
+++ b/2015-10-file-walker/Makefile
@@ -2,12 +2,10 @@ SHELL=/bin/bash
 
 ROOT_PATH=$(shell cd ~; pwd)
 
-OCAML_FILEUTILS_LIBDIR=$(shell ocamlfind query fileutils)
-
 all: ml_walker go_walker JavaWalker.class
 
-ml_walker: ml_walker.ml
-	ocamlopt -o ml_walker -I $(OCAML_FILEUTILS_LIBDIR) unix.cmxa fileutils-str.cmxa fileutils.cmxa ml_walker.ml
+ml_walker: ml_walker.ml check_ocaml_deps
+	ocamlopt -o ml_walker -I `ocamlfind query fileutils` unix.cmxa fileutils-str.cmxa fileutils.cmxa ml_walker.ml
 
 go_walker: go_walker.go
 	go build go_walker.go
@@ -15,16 +13,24 @@ go_walker: go_walker.go
 JavaWalker.class: JavaWalker.java
 	javac JavaWalker.java
 
-run: all
+test: all
 	echo "Root path is $(ROOT_PATH)"
-	time java JavaWalker $(ROOT_PATH)
-	time ./go_walker $(ROOT_PATH)
-	time ./ml_walker $(ROOT_PATH)
-	time python py_walker.py $(ROOT_PATH)
+	java JavaWalker $(ROOT_PATH)
+	./go_walker $(ROOT_PATH)
+	./ml_walker $(ROOT_PATH)
+	python py_walker.py $(ROOT_PATH)
+
+check_ocaml_deps:
+	@echo "checking OCaml dependencies..."
+	@if [[ `which ocamlopt` == '' ]]; then echo "Missing ocamlopt, install apt package 'ocaml'"; exit 1; fi
+	@if [[ `which ocamlfind` == '' ]]; then echo "Missing ocamlfind, install apt package 'ocaml-findlib'"; exit 1; fi
+	@if [[ `ocamlfind query fileutils` == '' ]]; then echo "Missing fileutils, need to install it manually - see README.rst for details"; exit 1; fi
+
+	@echo "dependency check successful."
 
 clean:
 	rm -f *~ ml_walker *.cmo *.cmx *.cmi *.o *.pyc go_walker \
 	      *.class
 
 
-.PHONY: clean all run
+.PHONY: clean all test check_ocaml_deps
